- name: Check the versions of wanted and venv's Python interpreters
  ansible.builtin.include_tasks: version.yml
  when: not python_virtualenv_force_recreate

- name: Remove the virtual environment
  ansible.builtin.file:
    path: "{{ python_virtualenv_dir }}"
    state: absent
  when: python_virtualenv_recreate

- name: Upgrade pip inside virtual environment
  ansible.builtin.pip:
    name: pip
    state: latest
    virtualenv: "{{ python_virtualenv_dir }}"
    virtualenv_command: "{{ python_virtualenv_command | default(omit) }}"
    virtualenv_python: "{{ python_virtualenv_python if python_virtualenv_command is not defined }}"
  when: python_virtualenv_upgrade_pip

- name: Install Python packages
  ansible.builtin.pip:
    name: "{{ python_virtualenv_packages }}"
    state: latest
    virtualenv: "{{ python_virtualenv_dir }}"
    virtualenv_command: "{{ python_virtualenv_command | default(omit) }}"
    virtualenv_python: "{{ python_virtualenv_python }}"
