- name: Install the 'numpy' package using the ansible-suite.python_virtualenv role
  hosts: all
  become: true
  roles:
    - ansible-suite.python_virtualenv
  vars:
    python_virtualenv_dir: /opt/virtualenv_numpy
    python_virtualenv_packages:
      - numpy
