- name: Install the 'ansible' package using the ansible-suite.python_virtualenv with 'python3 -m venv'
  hosts: all
  become: true
  roles:
    - ansible-suite.python_virtualenv
  vars:
    python_virtualenv_dir: /opt/venv_ansible
    python_virtualenv_packages:
      - ansible
    python_virtualenv_command: "{{ ansible_python_interpreter | default('python3') }} -m venv"
